# "docker compose -p echochat-staging -f docker-compose-staging.yml --env-file .env.staging up --build"          to run the compose file

version: "4"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-staging
    env_file:
      - .env.staging
    restart: unless-stopped
    depends_on:
      - db-postgres
      - db-redis
      - db-scylla-1
      - db-scylla-2
      - db-scylla-3
    ports:
      - "20011:8000"
    networks:
      - network-1

  db-postgres:
    image: postgres:15
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_DB=${POSTGRES_DB}'
      - 'POSTGRES_USER=${POSTGRES_USR}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PWD}'
      - 'PGDATA=/data/postgres'
      - POSTGRES_INITDB_ARGS="--auth-host=scram-sha-256"
    volumes:
      - postgres:/data/postgres
    networks:
      - network-1

  db-redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: 'redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PWD}'
    networks:
      - network-1

  db-scylla-1:
    image: scylladb/scylla
    restart: unless-stopped
    ports:
      - '9042:9042'
    #    volumes:
    #      - "./scylla/scylla.yaml:/etc/scylla/scylla.yaml"
    #      - "./scylla/cassandra-rackdc.properties.dc1:/etc/scylla/cassandra-rackdc.properties"
    #      - "./scylla/mutant-data.txt:/mutant-data.txt"
    command: --smp 1 --memory 1500M --overprovisioned 1
    networks:
      - network-1

  db-scylla-2:
    image: scylladb/scylla
    restart: unless-stopped
    depends_on:
      - db-scylla-1
    ports:
      - '9043:9042'
    #    volumes:
    #      - "./scylla/scylla.yaml:/etc/scylla/scylla.yaml"
    #      - "./scylla/cassandra-rackdc.properties.dc1:/etc/scylla/cassandra-rackdc.properties"
    command: --smp 1 --memory 1500M --overprovisioned 1 --seeds=db-scylla-1
    networks:
      - network-1

  db-scylla-3:
    image: scylladb/scylla
    restart: unless-stopped
    depends_on:
      - db-scylla-1
    ports:
      - '9044:9042'
    #    volumes:
    #      - "./scylla/scylla.yaml:/etc/scylla/scylla.yaml"
    #      - "./scylla/cassandra-rackdc.properties.dc1:/etc/scylla/cassandra-rackdc.properties"
    command: --smp 1 --memory 1500M --overprovisioned 1 --seeds=db-scylla-1
    networks:
      - network-1

networks:
  network-1:
    driver: bridge