global:
  scrape_interval:     15s 
  evaluation_interval: 15s 
scrape_configs:
  - job_name: 'prometheus-rmq'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'rabbitmq'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
    - targets: ['proto-rabbitmq:15692']